### PR TITLE
Support group synchronization from GitHub Teams

### PR DESCRIPTION
**Pull request by neverpanic**
In order to simplify our permission management and only have a single place to configure permissions, we've written a plugin to synchronize GitHub teams to Trac permission groups for the MacPorts Project.

The new code has full test coverage, does not introduce new pylint warnings and has been tested in production against Trac 1.0.13.

### CODE REVIEW

**Comment by aaugustin** [comment]
At a glance, this looks solid. (I can't say I read each of the 1500 added lines closely!) There's no risk of regressions since it only adds new functionality.

@rjollos Would you be OK with merging this PR and giving @neverpanic commit access to this repository?

**Comment by rjollos** [comment]
@aaugustin the feature looks good to me, and granting commit access to @neverpanic to merge the pull request sounds good.

Btw, I haven't forgotten about #102, so after that is merged I can create a new release that includes these changes as well.

**Comment by rjollos** [comment]
@neverpanic I sent you an invite to the trac-hacks organization, which will give you commit access to the trac-github repository.

**Comment by neverpanic** [comment]
Thanks. I'll see if I can add some tests for #102, too. It needs to be rebased anyway because of a (pretty trivial) conflict with this PR.

**Comment by aaugustin** [comment]
Welcome on board @neverpanic :-) The activity in this repo is rather low; feel free to move issues or pull requests forward, and in doubt ask @rjollos or myself. If you need permissions to push releases to PyPI I can arrange that as well, I'll just need your PyPI username.

**Comment by rjollos** [comment]
> Thanks. I'll see if I can add some tests for #102, too. It needs to be rebased anyway because of a (pretty trivial) conflict with this PR.

That would be great. Thanks!

Also on my long-term TODO list is to setup CI services, probably TravisCI and AppVeyor, both of which are used on the Trac project, but I'm open to other options as well. I'll probably make accounts with the CI services for the trac-hacks org on GitHub.

**Comment by neverpanic** [comment]
@aaugustin I don't have a PyPI username, but since the release frequency is rather low anyway I don't think that's a problem at the moment.

@rjollos CI would be great!

**Comment by rjollos** [comment]
I've installed the plugin to one of my sites and it still shows version 2.2, which is the same as the last-stable release. It would be good to bump the version at the start of development.

**Pull request merged**
